---
version: '2'
services:
  common:
    build: "."
    environment:
      RACK_ENV: production
  app:
    extends:
      service: common
    ports:
    - 3000:3000
    command: rails s -b 0.0.0.0
    links:
    - db
